'use strict';
'require view';
'require fs';
'require ui';

const helper='/usr/libexec/raywrt-usage-control';
const devices='/usr/libexec/raywrt-device-usage-control';
function parse(text){const [head,history='']=String(text||'').split('--HISTORY--');const state={};head.split('\n').forEach(l=>{const i=l.indexOf('=');if(i>0)state[l.slice(0,i)]=l.slice(i+1).trim();});state.history=history.trim().split('\n').filter(Boolean).map(l=>{const [date,down,up]=l.split(',');return {date,down:+down||0,up:+up||0};});return state;}
function parseDevices(text){const [head,body='']=String(text||'').split('--TODAY--');const [today='',tail='']=body.split('--HISTORY--');const [history='',meta='']=tail.split('--META--');const status={};head.split('\n').forEach(l=>{const i=l.indexOf('=');if(i>0)status[l.slice(0,i)]=l.slice(i+1).trim();});const rows=s=>s.trim().split('\n').filter(Boolean).map(l=>l.split(','));return {...status,today:rows(today).map(x=>({mac:x[0],down:+x[1]||0,up:+x[2]||0})),history:rows(history).map(x=>({date:x[0],mac:x[1],down:+x[2]||0,up:+x[3]||0})),meta:rows(meta).map(x=>({mac:x[0],name:x[1],ip:x[2],connection:x[3],lastSeen:+x[4]||0}))};}
function fmt(n){return n>=1e12?(n/1e12).toFixed(1)+' TB':n>=1e9?(n/1e9).toFixed(1)+' GB':n>=1e6?(n/1e6).toFixed(1)+' MB':n>=1e3?(n/1e3).toFixed(1)+' KB':Math.round(n||0)+' B';}
function choice(values,current){return E('select',{},values.map(([v,label])=>E('option',String(v)===String(current)?{value:v,selected:'selected'}:{value:v},label)));}
function sum(a){return a.reduce((n,x)=>n+x.down+x.up,0);}
function cutoff(day,n){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(n-1));return d.toISOString().slice(0,10);}
function table(headers,rows){return E('div',{class:'rw-table-scroll'},E('table',{class:'table'},[E('thead',{},E('tr',{},headers.map(x=>E('th',{},x)))),E('tbody',{},rows)]));}

return view.extend({
 addFooter(){},
 unload(){if(this.timer)clearInterval(this.timer);document.removeEventListener('visibilitychange',this.onVisibility);},
 load(){return Promise.all([L.resolveDefault(fs.exec(helper,['status']),{}),L.resolveDefault(fs.exec(devices,['status']),{})]);},
 render(results){
  this.data=parse(results[0].stdout);this.deviceData=parseDevices(results[1].stdout);
  this.selectedDevice=new URLSearchParams(window.location.search).get('device');this.tab=this.selectedDevice?'Devices':'Overview';this.windowDays=0;
  this.root=E('div',{class:'rw-tools rw-usage'},[E('h1',{},'Internet Data Usage'),E('p',{},'WAN totals and per-device Internet traffic. Live counters stay in RAM; daily aggregates are saved periodically.'),E('p',{id:'rw-usage-error',role:'status'}),E('nav',{class:'rw-usage-tabs',id:'rw-usage-tabs'}),E('div',{id:'rw-usage-content'})]);
  this.draw();this.onVisibility=()=>{if(!document.hidden&&this.root?.isConnected)this.refresh();};document.addEventListener('visibilitychange',this.onVisibility);this.timer=setInterval(()=>{if(!document.hidden)this.refresh();},60000);return this.root;
 },
 daily(){const s=this.data,today=s.date||'',current={date:today,down:+s.download||0,up:+s.upload||0};return s.history.filter(x=>x.date!==today).concat(current).sort((a,b)=>a.date.localeCompare(b.date));},
 deviceHistory(mac){const d=this.deviceData,all=d.history.filter(x=>x.mac===mac&&x.date!==d.date);const today=d.today.find(x=>x.mac===mac);if(today)all.push({...today,date:d.date});return all.sort((a,b)=>a.date.localeCompare(b.date));},
 period(mac,days){const all=this.deviceHistory(mac);return all.filter(x=>!days||x.date>=cutoff(this.deviceData.date,days)).reduce((v,x)=>({down:v.down+x.down,up:v.up+x.up}),{down:0,up:0});},
 draw(){if(!this.root)return;const tabs=this.root.querySelector('#rw-usage-tabs');tabs.replaceChildren(...['Overview','Devices','History','Diagnostics','Settings'].map(name=>E('button',{class:'btn'+(this.tab===name?' active':''),click:()=>{this.tab=name;this.selectedDevice=null;window.history.replaceState(null,'',window.location.pathname);this.draw();}},name)));
  const out=this.root.querySelector('#rw-usage-content');out.replaceChildren();
  if(this.tab==='Overview')this.drawOverview(out);else if(this.tab==='Devices')this.drawDevices(out);else if(this.tab==='History')this.drawHistory(out);else if(this.tab==='Diagnostics')this.drawDiagnostics(out);else this.drawSettings(out);
 },
 drawOverview(out){const all=this.daily(),today=all.at(-1)||{down:0,up:0},yesterday=all.find(x=>x.date===cutoff(this.data.date,2));out.append(E('div',{class:'rw-usage-summary'},[
  ...[['Today',today.down+today.up],['Yesterday',(yesterday?.down||0)+(yesterday?.up||0)],['Last 7 days',sum(all.filter(x=>x.date>=cutoff(this.data.date,7)))],['Last 30 days',sum(all.filter(x=>x.date>=cutoff(this.data.date,30)))],['Total Used',+this.data.total_recorded||0]].map(([label,value])=>E('section',{class:'rw-card'},[E('h2',{},label),E('strong',{},fmt(value))]))
 ]),E('section',{class:'rw-card'},[E('h2',{},'Today by direction'),E('p',{},'↓ Download '+fmt(today.down)+' · ↑ Upload '+fmt(today.up))]));},
 drawHistory(out){const all=this.daily().slice().reverse();const max=Math.max(1,...all.map(x=>x.down+x.up));const graph=E('svg',{viewBox:'0 0 600 120',preserveAspectRatio:'none',class:'rw-usage-graph','aria-label':'Daily Internet usage'},all.slice(0,30).reverse().map((x,i,a)=>E('rect',{x:String(i*600/a.length+2),y:String(116-(x.down+x.up)*108/max),width:String(Math.max(2,600/a.length-4)),height:String((x.down+x.up)*108/max),fill:'#55d998'})));out.appendChild(E('section',{class:'rw-card'},[E('h2',{},'Daily history'),graph,table(['Date','Download','Upload','Total'],all.map(x=>E('tr',{},[E('td',{},x.date),E('td',{},fmt(x.down)),E('td',{},fmt(x.up)),E('td',{},fmt(x.down+x.up))]))) ]));},
 drawDiagnostics(out){const d=this.data,rows=[['Router local date/time',d.router_time||'Unknown'],['Logical WAN',d.logical_wan||'Unknown'],['WAN device',d.wan_device||d.device||'Unknown'],['Underlying device',d.underlying_device||'Unknown'],['Current WAN RX',d.current_rx||'Unavailable'],['Current WAN TX',d.current_tx||'Unavailable'],['Last counter baseline RX',d.baseline_rx||'Unavailable'],['Last counter baseline TX',d.baseline_tx||'Unavailable'],['Today download',fmt(+d.download||0)],['Today upload',fmt(+d.upload||0)],['Per-device today total',fmt(+d.device_today_total||0)],['Accounting anomaly',d.usage_anomaly||'Unknown'],['Last saved',d.last_saved_local||'Not yet'],['Next save',d.next_save_local||'Unknown'],['WAN database',fmt(+d.database_bytes||0)]];out.appendChild(E('section',{class:'rw-card'},[E('h2',{},'Accounting diagnostics'),E('p',{},'All dates and save times come from the router clock. Counter restarts establish a new baseline to prevent double counting.'),table(['Check','Current value'],rows.map(([k,v])=>E('tr',{},[E('td',{},k),E('td',{},String(v))])))]));},
 drawDevices(out){if(this.selectedDevice){this.drawDetail(out,this.selectedDevice);return;}const d=this.deviceData,macs=new Set([...d.today.map(x=>x.mac),...d.history.map(x=>x.mac),...d.meta.map(x=>x.mac)]);const meta=new Map(d.meta.map(x=>[x.mac,x]));const select=choice([[0,'Today'],[7,'7 Days'],[30,'30 Days']],this.windowDays);select.addEventListener('change',()=>{this.windowDays=+select.value;this.draw();});const rows=[...macs].map(mac=>({mac,identity:meta.get(mac)||{},value:this.period(mac,this.windowDays)})).sort((a,b)=>(b.value.down+b.value.up)-(a.value.down+a.value.up));out.appendChild(E('section',{class:'rw-card'},[E('h2',{},'Devices'),E('label',{},['Sort period ',select]),table(['Device','MAC','Today','Last 7 days','Last 30 days'],rows.map(x=>E('tr',{},[
  E('td',{},E('button',{class:'rw-device-link',click:()=>{this.selectedDevice=x.mac;window.history.replaceState(null,'','?device='+encodeURIComponent(x.mac));this.draw();}},x.identity.name||'Unknown Device')),
  E('td',{},x.mac),E('td',{},fmt(sum(this.deviceHistory(x.mac).filter(v=>v.date===d.date)))),E('td',{},fmt(sum(this.deviceHistory(x.mac).filter(v=>v.date>=cutoff(d.date,7))))),E('td',{},fmt(sum(this.deviceHistory(x.mac).filter(v=>v.date>=cutoff(d.date,30)))))
 ])))]));},
 drawDetail(out,mac){const d=this.deviceData,m=d.meta.find(x=>x.mac===mac)||{},all=this.deviceHistory(mac),today=this.period(mac,1),yesterday=all.find(x=>x.date===cutoff(d.date,2))||{down:0,up:0},last7=this.period(mac,7),last30=this.period(mac,30);const max=Math.max(1,...all.map(x=>x.down+x.up));const bars=all.slice(-30).map((x,i,a)=>E('rect',{x:String(i*600/a.length+2),y:String(116-(x.down+x.up)*108/max),width:String(Math.max(2,600/a.length-4)),height:String((x.down+x.up)*108/max),fill:'#55d998'}));out.append(E('button',{class:'btn',click:()=>{this.selectedDevice=null;window.history.replaceState(null,'',window.location.pathname);this.draw();}},'← All devices'),E('section',{class:'rw-card rw-device-detail'},[E('h2',{},m.name||'Unknown Device'),E('p',{},mac+' · '+(m.ip||'IP unavailable')+' · '+(m.connection||'Connection unknown')),E('p',{},'Last seen: '+(m.lastSeen?new Date(m.lastSeen*1000).toLocaleString():'Unknown')),table(['Period','Download','Upload','Total'],[['Today',today],['Yesterday',yesterday],['Last 7 days',last7],['Last 30 days',last30]].map(([label,v])=>E('tr',{},[E('td',{},label),E('td',{},fmt(v.down)),E('td',{},fmt(v.up)),E('td',{},fmt(v.down+v.up))]))),E('h3',{},'Daily usage'),E('svg',{viewBox:'0 0 600 120',preserveAspectRatio:'none',class:'rw-usage-graph','aria-label':'Per-device daily Internet usage'},bars)]));},
 drawSettings(out){const s=this.data,enabled=choice([['1','On'],['0','Off']],s.enabled||'1'),retention=choice([1,3,7,14,30,60,90,180,365,'never'].map(x=>[x,x==='never'?'Never automatically delete':x+' day'+(x===1?'':'s')]),s.retention||'30'),interval=choice([[15,'15 minutes'],[30,'30 minutes'],[60,'60 minutes']],s.save_minutes||'30');out.appendChild(E('section',{class:'rw-card rw-usage-settings'},[E('h2',{},'Data Usage Settings'),E('label',{},['Traffic accounting ',enabled]),E('label',{},['Keep history ',retention]),E('label',{},['Save interval ',interval]),E('p',{},'Stored days: '+(s.stored_days||0)+' · WAN database: '+fmt(+s.database_bytes||0)+' · Device database: '+fmt(+s.device_database_bytes||0)+' · Device metadata: '+fmt(+this.deviceData.metadata_bytes||0)),E('p',{},'Last saved (router time): '+(s.last_saved_local||'Not yet')+' · Next scheduled save: '+(s.next_save_local||'—')),E('p',{},'A sudden power loss can lose up to one save interval of recent usage.'),E('button',{class:'btn cbi-button-positive',click:()=>this.configure(enabled.value,retention.value,interval.value)},'Save settings'),E('button',{class:'btn cbi-button-negative',click:()=>this.confirmClear()},'Clear Usage History')]));},
 async refresh(){if(!this.root?.isConnected||this.refreshing)return;this.refreshing=true;const error=this.root.querySelector('#rw-usage-error');try{const [r,d]=await Promise.all([fs.exec(helper,['status']),fs.exec(devices,['status'])]);if(r.code!==0||d.code!==0)throw Error(r.stderr||d.stderr||'Usage status unavailable');this.data=parse(r.stdout);this.deviceData=parseDevices(d.stdout);this.draw();error.textContent='';}catch(e){error.textContent=e.message;}finally{this.refreshing=false;}},
 unload(){if(this.timer)clearInterval(this.timer);document.removeEventListener('visibilitychange',this.onVisibility);},
 async configure(enabled,retention,interval){try{const r=await fs.exec(helper,['configure',enabled,retention,interval]);if(r.code!==0)throw Error(r.stderr||'Could not save settings');this.refresh();}catch(e){ui.addNotification(null,E('p',{},e.message));}},
 confirmClear(){ui.showModal('Clear traffic history?',E('div',{},[E('p',{},'This permanently removes WAN and per-device usage history.'),E('div',{class:'right'},[E('button',{class:'btn',click:()=>ui.hideModal()},'Cancel'),E('button',{class:'btn cbi-button-negative',click:async()=>{ui.hideModal();try{const r=await fs.exec(helper,['clear']);if(r.code!==0)throw Error(r.stderr||'Could not clear history');this.refresh();}catch(e){ui.addNotification(null,E('p',{},e.message));}}},'Clear')])]))},
});
