package io.github.heygoodbye.raywrt;
import android.app.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.text.InputType;
import android.text.method.PasswordTransformationMethod;
import android.view.*;
import android.widget.*;
import java.util.*;

final class ToolsPanel extends LinearLayout {
 interface Host{void run(String command,String success,Runnable after);void ping();boolean connected();}
 final Activity context;final Host host;final LinearLayout pingResults,wifi;final List<View> controls=new ArrayList<>();boolean busy;String selectedWifi;
 ToolsPanel(Activity c,Host h){super(c);context=c;host=h;setOrientation(VERTICAL);
  LinearLayout ping=card("Ping Test","Test 15 EU Gaming Servers","ping");Button test=button("Run test",ping);test.setOnClickListener(v->{if(host.connected())host.ping();});pingResults=column();pingResults.addView(label("Run a test to measure ping and replies.",13));ping.addView(pingResults);addView(ping);
  LinearLayout wireless=card("Wireless","Manage your Wi-Fi networks","wifi");wifi=column();wireless.addView(wifi);addView(wireless);render(Collections.emptyList());
  LinearLayout system=card("Router system","Restart your router safely","modem");Button reboot=button("Reboot router",system);reboot.setTextSize(15);reboot.setTextColor(0xffffe1df);reboot.setBackground(background(0xff392328,0xff96565c,10));reboot.setOnClickListener(v->{if(!host.connected())return;new AlertDialog.Builder(c).setTitle("Reboot router?").setMessage("All connections will be interrupted while the router restarts.").setNegativeButton("Cancel",null).setPositiveButton("Reboot",(d,w)->host.run(RouterTools.REBOOT,"Reboot requested. Reconnect after the router starts.",null)).show();});addView(system);
 }
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 LinearLayout column(){LinearLayout p=new LinearLayout(context);p.setOrientation(VERTICAL);return p;}
 GradientDrawable background(int fill,int border,int radius){GradientDrawable b=new GradientDrawable();b.setColor(fill);b.setCornerRadius(dp(radius));b.setStroke(dp(1),border);return b;}
 TextView label(String s,int size){TextView t=new TextView(context);t.setText(s);t.setTextSize(size);t.setTextColor(size>=18?0xffedf3f2:0xffa4b6b1);t.setTypeface(Typeface.create(size>=18?"sans-serif-medium":"sans-serif",Typeface.NORMAL));t.setIncludeFontPadding(false);t.setPadding(0,dp(6),0,dp(8));return t;}
 LinearLayout card(String title,String sub,String icon){LinearLayout p=column();p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackground(background(0xff121e21,0xff283735,17));LayoutParams lp=new LayoutParams(-1,-2);lp.bottomMargin=dp(16);p.setLayoutParams(lp);LinearLayout heading=new LinearLayout(context);heading.setGravity(Gravity.CENTER_VERTICAL);FrameLayout iconBox=new FrameLayout(context);iconBox.setBackground(background(0xff1c322b,0xff1c322b,10));iconBox.addView(new ToolIcon(icon),new FrameLayout.LayoutParams(dp(20),dp(20),Gravity.CENTER));heading.addView(iconBox,new LayoutParams(dp(36),dp(36)));LinearLayout copy=column();TextView name=label(title,19);copy.addView(name);copy.addView(label(sub,12));LayoutParams np=new LayoutParams(0,-2,1);np.leftMargin=dp(12);heading.addView(copy,np);p.addView(heading);return p;}
 final class ToolIcon extends View{
  final String type;final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);
  ToolIcon(String type){super(context);this.type=type;paint.setColor(0xff75dda9);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(1.6f);paint.setStrokeCap(Paint.Cap.ROUND);setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);}
  protected void onDraw(Canvas c){c.save();c.scale(getWidth()/24f,getHeight()/24f);if(type.equals("wifi")){c.drawArc(2,4,22,24,215,110,false,paint);c.drawArc(6,9,18,21,215,110,false,paint);c.drawPoint(12,18,paint);}else if(type.equals("modem")){c.drawLine(4,13,4,4,paint);c.drawLine(20,13,20,4,paint);c.drawRoundRect(1,13,23,22,2,2,paint);c.drawLine(5,18,6,18,paint);c.drawLine(10,18,11,18,paint);c.drawLine(18,18,20,18,paint);}else{Path p=new Path();p.moveTo(1,12);p.lineTo(6,12);p.lineTo(9,4);p.lineTo(14,20);p.lineTo(18,12);p.lineTo(23,12);c.drawPath(p,paint);}c.restore();}
 }
 Button button(String title,LinearLayout parent){Button b=new Button(context);b.setAllCaps(false);b.setText(title);b.setTextSize(14);b.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));b.setTextColor(0xffcbf3de);b.setStateListAnimator(null);b.setElevation(0);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(10),0,dp(10),0);b.setBackground(new RippleDrawable(android.content.res.ColorStateList.valueOf(0x2465e5b0),background(0xff203d2f,0xff3b664a,10),null));LayoutParams lp=new LayoutParams(-1,dp(48));lp.topMargin=dp(10);lp.bottomMargin=dp(12);parent.addView(b,lp);controls.add(b);return b;}
 void styleField(EditText e){e.setTextSize(14);e.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));e.setPadding(dp(12),dp(12),dp(12),dp(12));e.setBackground(background(0xff111c1e,0xff2c3d3e,10));e.setMinimumHeight(dp(48));e.setSingleLine(true);e.setTextColor(Color.WHITE);}
 void setBusy(boolean value){busy=value;for(View v:controls){v.setEnabled(!value&&host.connected());v.setAlpha(1f);}}
 void pingStarted(){pingResults.removeAllViews();pingResults.addView(label("Testing 15 servers…",13));}
 void pingFailed(){pingResults.removeAllViews();pingResults.addView(label("Test failed. Try again.",13));}
 void renderPing(RouterTools.PingResult r){
  controls.removeIf(v->"ping".equals(v.getTag()));pingResults.removeAllViews();LinearLayout metrics=new LinearLayout(context);String[]labels={"Average ping","Server replies","Packet loss"},values={r.average,r.replies+"/15",r.loss},notes={"Responding servers","Targets reached",r.counts};
  for(int i=0;i<3;i++){LinearLayout tile=column();tile.setPadding(dp(8),dp(8),dp(8),dp(6));tile.setBackground(background(0xff111c1e,0xff2c3d3e,10));tile.addView(label(labels[i],11));TextView value=label(values[i],i==0?21:20);value.setTextColor(i==0?0xff85e2b0:0xffedf3f2);tile.addView(value);tile.addView(label(notes[i],10));LayoutParams p=new LayoutParams(0,-1,1);p.leftMargin=i==0?0:dp(3);p.rightMargin=i==2?0:dp(3);metrics.addView(tile,p);}pingResults.addView(metrics);pingResults.addView(label("Packet loss is measured on responding servers. Nonresponding targets are listed separately.",12));pingResults.addView(label(r.replies==15?"All 15 servers replied.":(15-r.replies)+(r.replies==14?" target did not reply.":" targets did not reply."),12));Button details=button("View server results",pingResults);details.setTag("ping");details.setOnClickListener(v->{ScrollView scroll=new ScrollView(context);TextView text=label(r.details,13);text.setTextIsSelectable(true);text.setPadding(dp(20),dp(12),dp(20),dp(12));scroll.addView(text);new AlertDialog.Builder(context).setTitle("Ping Test · server results").setView(scroll).setPositiveButton("Close",null).show();});setBusy(busy);
 }
 void render(List<RouterTools.Wifi> networks){
  controls.removeIf(v->"wifi".equals(v.getTag()));wifi.removeAllViews();if(networks.isEmpty()){wifi.addView(label("Connect to read your router's Wi-Fi settings.",13));setBusy(busy);return;}
  RouterTools.Wifi selected=null;for(RouterTools.Wifi w:networks)if(w.id.equals(selectedWifi))selected=w;if(selected==null)for(RouterTools.Wifi w:networks)if(w.enabled&&Boolean.TRUE.equals(w.up)){selected=w;break;}if(selected==null)for(RouterTools.Wifi w:networks)if(w.enabled){selected=w;break;}if(selected==null)selected=networks.get(0);final RouterTools.Wifi chosen=selected;selectedWifi=chosen.id;
  LinearLayout bands=new LinearLayout(context);wifi.addView(bands);Map<String,List<RouterTools.Wifi>> groups=new LinkedHashMap<>();for(RouterTools.Wifi w:networks)groups.computeIfAbsent(w.radio,k->new ArrayList<>()).add(w);
  for(List<RouterTools.Wifi> group:groups.values()){
   RouterTools.Wifi candidate=group.get(0);for(RouterTools.Wifi w:group)if(w.enabled){candidate=w;break;}for(RouterTools.Wifi w:group)if(w.id.equals(chosen.id)){candidate=w;break;}final RouterTools.Wifi w=candidate;boolean active=w.radio.equals(chosen.radio);LinearLayout tile=column();tile.setPadding(dp(10),dp(10),dp(10),dp(10));tile.setBackground(background(active?0xff152c24:0xff131e22,active?0xff457a56:0xff2a3936,12));LayoutParams tp=new LayoutParams(0,-2,1);tp.setMargins(dp(2),dp(12),dp(2),dp(12));bands.addView(tile,tp);
   TextView band=label(w.band,14);band.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));band.setTextColor(0xffedf3f2);tile.addView(band);TextView state=label("●  "+w.state(),12);state.setTextColor(w.enabled&&!Boolean.FALSE.equals(w.up)?0xff85e2b0:0xff9eacaf);tile.addView(state);tile.setContentDescription("Select "+w.band);tile.setOnClickListener(v->{selectedWifi=w.id;render(networks);});
   Button toggle=button(w.enabled?"Disable":"Enable",tile);toggle.setTextSize(13);toggle.setBackground(background(w.enabled?0xff203d2f:0xff1a272a,w.enabled?0xff3b664a:0xff354542,10));toggle.setTextColor(w.enabled?0xffa3e4bd:0xffd6e5df);toggle.setContentDescription((w.enabled?"Disable ":"Enable ")+w.band);toggle.setTag("wifi");controls.add(tile);tile.setTag("wifi");toggle.setOnClickListener(v->{if(!host.connected())return;new AlertDialog.Builder(context).setTitle((w.enabled?"Disable ":"Enable ")+w.band+"?").setMessage("This changes the radio and may disconnect you. Other networks on this radio are affected.").setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,x)->{selectedWifi=w.id;host.run(RouterTools.toggle(w,!w.enabled),"Wi-Fi state refreshed. Reconnect if needed.",null);}).show();});
  }
  wifi.addView(label(chosen.band+" network",16));List<RouterTools.Wifi> siblings=groups.get(chosen.radio);if(siblings.size()>1){Spinner selector=new Spinner(context);selector.setAdapter(new ArrayAdapter<>(context,android.R.layout.simple_spinner_dropdown_item,siblings));selector.setSelection(siblings.indexOf(chosen));wifi.addView(selector);selector.setTag("wifi");controls.add(selector);selector.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int index,long id){RouterTools.Wifi next=siblings.get(index);if(!next.id.equals(selectedWifi)){selectedWifi=next.id;render(networks);}}});}
  wifi.addView(label("Network name (SSID)",13));EditText ssid=new EditText(context);styleField(ssid);ssid.setText(chosen.ssid);ssid.setContentDescription("Wi-Fi SSID");wifi.addView(ssid);ssid.setTag("wifi");controls.add(ssid);
  wifi.addView(label("Wi-Fi password",13));LinearLayout passwordRow=new LinearLayout(context);passwordRow.setGravity(Gravity.CENTER_VERTICAL);EditText password=new EditText(context);styleField(password);password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);password.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));password.setText(chosen.key);password.setSaveEnabled(false);password.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);password.setContentDescription("Wi-Fi password");passwordRow.addView(password,new LayoutParams(0,-2,1));password.setTag("wifi");controls.add(password);Button reveal=button("Show",passwordRow);LayoutParams rp=new LayoutParams(dp(66),dp(48));rp.leftMargin=dp(8);reveal.setLayoutParams(rp);reveal.setTag("wifi");reveal.setOnClickListener(v->{boolean show=password.getTransformationMethod()!=null;password.setTransformationMethod(show?null:PasswordTransformationMethod.getInstance());password.setSelection(password.getText().length());reveal.setText(show?"Hide":"Show");});wifi.addView(passwordRow);
  wifi.addView(label(chosen.encryption.equals("none")?"Open network · no password configured.":chosen.key.isEmpty()?"The router did not return a stored password.":"Current router password loaded · hidden by default.",12));wifi.addView(label("Wi-Fi changes may disconnect you. Clearing the field preserves the current password.",12));Button save=button("Save changes",wifi);save.setTag("wifi");save.setOnClickListener(v->{if(!host.connected())return;try{String cmd=RouterTools.save(chosen,ssid.getText().toString(),password.getText().toString());new AlertDialog.Builder(context).setTitle("Save Wi-Fi changes?").setMessage("Update "+chosen.band+" · "+chosen.ssid+"? You may need to reconnect using the new settings.").setNegativeButton("Cancel",null).setPositiveButton("Save",(d,x)->host.run(cmd,"Wi-Fi settings saved. Reconnect using the new settings if needed.",null)).show();}catch(Exception e){new AlertDialog.Builder(context).setMessage(e.getMessage()).setPositiveButton("OK",null).show();}});setBusy(busy);
 }
}
