#!/bin/sh
printf '\033[1;32m'
printf '  RayWRT\033[0m\n\n'
. /etc/openwrt_release
printf '  RayWRT 1.0.0  |  %s  |  %s\n\n' "$(uname -n)" "$DISTRIB_DESCRIPTION"
export PS1='\[\033[1;32m\]root@RayWRT\[\033[0m\]:\w# '
exec /bin/ash -i
