#!/bin/sh /etc/rc.common
USE_PROCD=1
START=91
STOP=10
start_service() {
  procd_open_instance
  procd_set_param command /usr/libexec/raywrt-device-usage
  procd_set_param respawn 3600 5 5
  procd_close_instance
}
