import pathlib,time
src=pathlib.Path('android/tests/emulator_test.py').read_text(encoding='utf-8-sig')
exec(src.split("wait_text('Disconnected')")[0])
wait_text('Disconnected')
set_text('Router IP or hostname','10.0.2.2');set_text('SSH password','fixture');tap(text='Connect')
time.sleep(1)
if any(n.get('text')=='Trust this router?' for n in dump()):tap(text='Trust')
wait_text('Connected · Router configurations loaded')
tap(text='WireGuard');node(desc='Import WireGuard configuration');tap(desc='Import WireGuard configuration')
node(text='Import WireGuard');node(text='WireGuard .conf');node(text='Choose .conf file')
screenshot('wireguard-import-android.png')
tap(text='Import')
node(text='Paste a WireGuard .conf file up to 64 KB.')
tap(text='Cancel')
print('PASS: Android WireGuard import tab, file/paste dialog and validation')
