using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
namespace RayWRT.Companion;
public partial class MainWindow
{
 StackPanel wifiContent=new(),pingResults=new();TextBlock pingResult=new();Border toolsPanel=new();Button routerTab=new();string? selectedWifi;
 void InitializeTools(){
  var tabs=(Grid)PassTab.Parent;tabs.ColumnDefinitions.Add(new());var tabCopy=new StackPanel{Orientation=Orientation.Horizontal};tabCopy.Children.Add(ToolIcon("RouterIcon",17));tabCopy.Children.Add(new TextBlock{Text="Router",Margin=new Thickness(7,0,0,0),VerticalAlignment=VerticalAlignment.Center});routerTab.Content=tabCopy;routerTab.Style=(Style)FindResource("QuietButton");routerTab.Padding=new Thickness(10);Grid.SetColumn(routerTab,2);tabs.Children.Add(routerTab);routerTab.Click+=(_,_)=>SelectTools();
  var cards=new StackPanel();toolsPanel.Child=cards;toolsPanel.Visibility=Visibility.Collapsed;BodyContent.Children.Add(toolsPanel);
  var ping=ToolCard("Ping Test","Test 15 EU Gaming Servers","GlobeIcon");var test=ToolButton("Run test",ping);test.Click+=async(_,_)=>await Run(async()=>{Status.Text="Testing 15 servers…";Empty(pingResults,"Testing 15 servers…");using var stream=typeof(MainWindow).Assembly.GetManifestResourceStream("RayWRT.Diagnostics")!;using var reader=new StreamReader(stream);SetPingResult(RouterTools.Ping(await Command("sh -c "+Quote(await reader.ReadToEndAsync())+" raywrt run")));Status.Text="Diagnostic complete · 15 targets tested";});ping.Children.Add(pingResults);Empty(pingResults,"Run a test to measure ping and replies.");cards.Children.Add(WrapTool(ping));
  var wifi=ToolCard("Wireless","Manage your Wi-Fi networks","WifiIcon");wifi.Children.Add(wifiContent);cards.Children.Add(WrapTool(wifi));Empty(wifiContent,"Connect to read your router's Wi-Fi settings.");
  var system=ToolCard("Router system","Restart your router safely","RouterIcon");var reboot=ToolButton("Reboot router",system);reboot.FontSize=15;reboot.Foreground=Brush("#FFE1DF");reboot.Background=Brush("#392328");reboot.BorderBrush=Brush("#96565C");reboot.Click+=async(_,_)=>{if(client?.IsConnected!=true){Status.Text="Connect to your router first.";return;}if(MessageBox.Show(this,"All connections will be interrupted while the router restarts.","Reboot router?",MessageBoxButton.OKCancel,MessageBoxImage.Warning)!=MessageBoxResult.OK)return;await Run(async()=>{await Command(RouterTools.Reboot);client?.Dispose();client=null;Connection.Content="Connect";LoginPanel.Visibility=Visibility.Visible;Host.IsReadOnly=false;Toggle.IsEnabled=false;Empty(wifiContent,"Connect to read your router's Wi-Fi settings.");Status.Text="Reboot requested. Reconnect after the router starts.";});};cards.Children.Add(WrapTool(system));
 }
 Image ToolIcon(string key,int size)=>new(){Source=(ImageSource)FindResource(key),Width=size,Height=size,VerticalAlignment=VerticalAlignment.Center};
 Border WrapTool(StackPanel p)=>new(){Child=p,Style=(Style)FindResource("Section"),Margin=new Thickness(0,0,0,16)};
 TextBlock ToolText(string text,double size)=>new(){Text=text,FontSize=size,FontWeight=size>=18?FontWeights.SemiBold:FontWeights.Normal,TextWrapping=TextWrapping.Wrap,Foreground=Brush(size>=18?"#EDF3F2":"#A4B6B1"),Margin=new Thickness(0,4,0,8)};
 StackPanel ToolCard(string title,string subtitle,string icon){var p=new StackPanel();var heading=new StackPanel{Orientation=Orientation.Horizontal};heading.Children.Add(new Border{Child=ToolIcon(icon,20),Width=36,Height=36,CornerRadius=new CornerRadius(10),Background=Brush("#1C322B"),Margin=new Thickness(0,0,12,0)});var copy=new StackPanel();copy.Children.Add(ToolText(title,21));copy.Children.Add(ToolText(subtitle,13));heading.Children.Add(copy);p.Children.Add(heading);return p;}
 Button ToolButton(string text,StackPanel p){var b=new Button{Content=text,FontSize=14,FontWeight=FontWeights.SemiBold,MinHeight=44,Padding=new Thickness(12,11,12,11),Margin=new Thickness(0,10,0,12),HorizontalAlignment=HorizontalAlignment.Stretch,Background=Brush("#203D2F"),BorderBrush=Brush("#3B664A"),Foreground=Brush("#CBF3DE")};p.Children.Add(b);return b;}
 void SetPingResult(RouterTools.PingResult report){
  pingResult.Text=$"{report.Average} · {report.Replies}/15 replies · {report.Loss}";pingResults.Children.Clear();var metrics=new Grid();for(int i=0;i<3;i++)metrics.ColumnDefinitions.Add(new());
  string[] labels={"Average ping","Server replies","Packet loss"},values={report.Average,$"{report.Replies}/15",report.Loss},notes={"Responding servers","Targets reached",report.Counts};
  for(int i=0;i<3;i++){var copy=new StackPanel();copy.Children.Add(ToolText(labels[i],12));var value=ToolText(values[i],i==0?23:21);value.Foreground=Brush(i==0?"#85E2B0":"#EDF3F2");copy.Children.Add(value);copy.Children.Add(ToolText(notes[i],11));var tile=new Border{Child=copy,Padding=new Thickness(10),CornerRadius=new CornerRadius(10),Background=Brush("#111C1E"),BorderBrush=Brush("#2C3D3E"),BorderThickness=new Thickness(1),Margin=new Thickness(i==0?0:4,0,i==2?0:4,0)};Grid.SetColumn(tile,i);metrics.Children.Add(tile);}pingResults.Children.Add(metrics);
  pingResults.Children.Add(ToolText("Packet loss is measured on responding servers. Nonresponding targets are listed separately.",12));pingResults.Children.Add(ToolText(report.Replies==15?"All 15 servers replied.":$"{15-report.Replies} "+(report.Replies==14?"target did not reply.":"targets did not reply."),12));var details=ToolButton("View server results",pingResults);details.Background=Brush("#172423");details.Click+=(_,_)=>MessageBox.Show(this,report.Details,"Ping Test · server results",MessageBoxButton.OK,MessageBoxImage.Information);
 }
 void SelectTools(){PassPanel.Visibility=Visibility.Collapsed;WirePanel.Visibility=Visibility.Collapsed;toolsPanel.Visibility=Visibility.Visible;PassTab.Background=WireTab.Background=Brush("#00101A1C");PassTab.BorderBrush=WireTab.BorderBrush=Brush("#00101A1C");routerTab.Background=Brush("#214333");routerTab.BorderBrush=Brush("#416B50");ContentScroll.ScrollToTop();}
 void HideTools(){toolsPanel.Visibility=Visibility.Collapsed;WirePanel.Visibility=Visibility.Visible;routerTab.Background=Brush("#00101A1C");routerTab.BorderBrush=Brush("#00101A1C");}
 async Task ApplyWifi(string command,string message){await Command(command);Status.Text="Wi-Fi saved. Checking live state…";await Task.Delay(3500);try{await Refresh();Status.Text=message;}catch{Empty(wifiContent,"Settings saved. Reconnect and Refresh to read the live Wi-Fi state.");Status.Text=message;}}
 void RenderWifi(List<RouterTools.Wifi> networks){
  wifiContent.Children.Clear();if(networks.Count==0){Empty(wifiContent,"No Wi-Fi access points configured.");return;}
  var chosen=networks.FirstOrDefault(w=>w.Id==selectedWifi)??networks.FirstOrDefault(w=>w.Enabled&&w.Up==true)??networks.FirstOrDefault(w=>w.Enabled)??networks[0];selectedWifi=chosen.Id;
  var bands=new Grid();int index=0;foreach(var group in networks.GroupBy(w=>w.Radio)){
   bands.ColumnDefinitions.Add(new());var w=group.FirstOrDefault(w=>w.Id==chosen.Id)??group.FirstOrDefault(w=>w.Enabled)??group.First();bool selected=w.Radio==chosen.Radio;
   var copy=new StackPanel();var name=new StackPanel{Orientation=Orientation.Horizontal};name.Children.Add(ToolIcon("WifiIcon",16));name.Children.Add(new TextBlock{Text=w.Band,FontSize=14,FontWeight=FontWeights.SemiBold,Margin=new Thickness(7,0,0,0)});copy.Children.Add(name);
   var state=ToolText("●  "+w.State,12);state.Foreground=Brush(w.Enabled&&w.Up!=false?"#85E2B0":"#9EACAF");copy.Children.Add(state);
   var toggle=ToolButton(w.Enabled?"Disable":"Enable",copy);toggle.FontSize=13;toggle.MinHeight=38;toggle.Padding=new Thickness(8);toggle.Margin=new Thickness(0,4,0,0);toggle.Background=Brush(w.Enabled?"#203D2F":"#1A272A");toggle.BorderBrush=Brush(w.Enabled?"#3B664A":"#354542");toggle.Foreground=Brush(w.Enabled?"#A3E4BD":"#D6E5DF");
   var card=new Border{Child=copy,Background=Brush(selected?"#152C24":"#131E22"),BorderBrush=Brush(selected?"#457A56":"#2A3936"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Padding=new Thickness(12),Margin=new Thickness(index==0?0:4,12,4,14),Cursor=System.Windows.Input.Cursors.Hand};Grid.SetColumn(card,index++);bands.Children.Add(card);card.MouseLeftButtonUp+=(_,e)=>{if(IsWindowControl(e.OriginalSource as DependencyObject))return;selectedWifi=w.Id;RenderWifi(networks);};
   toggle.Click+=async(_,_)=>{if(client?.IsConnected!=true){Status.Text="Connect to your router first.";return;}if(MessageBox.Show(this,"This changes the radio and may disconnect you. Other networks on this radio are affected.",(w.Enabled?"Disable ":"Enable ")+w.Band+"?",MessageBoxButton.OKCancel,MessageBoxImage.Warning)!=MessageBoxResult.OK)return;selectedWifi=w.Id;await Run(()=>ApplyWifi(RouterTools.Toggle(w,!w.Enabled),"Wi-Fi state refreshed. Reconnect if needed."));};
  }wifiContent.Children.Add(bands);wifiContent.Children.Add(ToolText(chosen.Band+" network",16));
  var siblings=networks.Where(w=>w.Radio==chosen.Radio).ToList();if(siblings.Count>1){var selector=new ComboBox{Style=(Style)FindResource("WifiSelector"),ItemsSource=siblings,SelectedItem=chosen,FontSize=14,Margin=new Thickness(0,0,0,10)};wifiContent.Children.Add(selector);selector.SelectionChanged+=(_,_)=>{if(selector.SelectedItem is RouterTools.Wifi selected){selectedWifi=selected.Id;RenderWifi(networks);}};}
  wifiContent.Children.Add(ToolText("Network name (SSID)",13));var ssid=new TextBox{Text=chosen.Ssid,FontSize=14};wifiContent.Children.Add(ssid);
  wifiContent.Children.Add(ToolText("Wi-Fi password",13));var secret=new PasswordBox{Password=chosen.Key,FontSize=14};var revealed=new TextBox{Text=chosen.Key,FontSize=14,Visibility=Visibility.Collapsed};var secretGrid=new Grid();secretGrid.ColumnDefinitions.Add(new());secretGrid.ColumnDefinitions.Add(new(){Width=GridLength.Auto});secretGrid.Children.Add(secret);secretGrid.Children.Add(revealed);var show=new Button{Content="Show",FontSize=13,Padding=new Thickness(12),Margin=new Thickness(8,0,0,0)};Grid.SetColumn(show,1);secretGrid.Children.Add(show);show.Click+=(_,_)=>{bool reveal=secret.Visibility==Visibility.Visible;if(reveal)revealed.Text=secret.Password;else secret.Password=revealed.Text;secret.Visibility=reveal?Visibility.Collapsed:Visibility.Visible;revealed.Visibility=reveal?Visibility.Visible:Visibility.Collapsed;show.Content=reveal?"Hide":"Show";};wifiContent.Children.Add(secretGrid);
  wifiContent.Children.Add(ToolText(chosen.Encryption=="none"?"Open network · no password configured.":chosen.Key==""?"The router did not return a stored password.":"Current router password loaded · hidden by default.",12));
  wifiContent.Children.Add(ToolText("Wi-Fi changes may disconnect you. Clearing the field preserves the current password.",12));var save=ToolButton("Save changes",wifiContent);save.Click+=async(_,_)=>{string command;try{command=RouterTools.Save(chosen,ssid.Text,secret.Visibility==Visibility.Visible?secret.Password:revealed.Text);}catch(Exception ex){Status.Text=ex.Message;return;}if(MessageBox.Show(this,"Update "+chosen.Band+" · "+chosen.Ssid+"? You may need to reconnect using the new settings.","Save Wi-Fi changes?",MessageBoxButton.OKCancel,MessageBoxImage.Warning)!=MessageBoxResult.OK)return;await Run(()=>ApplyWifi(command,"Wi-Fi settings saved. Reconnect using the new settings if needed."));};
 }
}
